name: Create Branch From Development For Issue

on:
  issues:
    types:
      - assigned

jobs:
  create-branch:
    runs-on: ubuntu-latest
    # if: contains(github.event.issue.labels.*.name, 'bug') && github.event_name == 'issues' && (github.event.action == 'labeled' || github.event.action == 'opened')
    steps:
      # checkout the code
      - name: ğŸ›ï¸ Checkout Code
        uses: actions/checkout@v2
        
      # create a branch
      - name: ğŸŒ¿ğŸ‘† Create branch and push 
        run: 
          branch_name="bug/${{ github.event.issue.number }}-${{ github.event.issue.title }}"
          git checkout production
          git pull origin production
          git checkout -b "bug/${{ github.event.issue.number }}-${{ github.event.issue.title }}"
          git push origin "bug/${{ github.event.issue.number }}-${{ github.event.issue.title }}"

      # print
      - name: ğŸ‰ Completed
        run: echo Successfully Created a Branch! ğŸŠ
